feat:page not found with butt
Bunyod16/42-on-campus-stats pull request #1
Opened 2022-12-13 08:37 UTC by jasonkwm

page not found with butt gif

2022-12-13 09:39 UTC, Bunyod16 submitted a review, later dismissed

2022-12-13 09:42 UTC, Bunyod16 requested changes
backend/.env file was added, supposed to not be tracked

2022-12-28 06:52 UTC, jasonkwm commented
@Bunyod16 How did u ignore venv and stuff without gitignore? and why is banana yellow?

2022-12-28 08:10 UTC, Bunyod16 approved these changes

2022-12-28 08:11 UTC, merged